@startuml
hide circle

Class Account {
    username: String
    password: String
}

Class Person {
    name: String
}

Class Game {
    score: int
}

Class Round {
    id: int
    word: Word
}

class RoundDTO {
}

enum Role <<Enumeration>> {
    PLAYER
    ADMINISTRATOR
    HEAD_ADMINISTRATOR
}

enum FeedbackItem <<Enumeration>> {
    INVALID
    CORRECT
    PRESENT
    ABSENT
}

Class Feedback {
}

enum Letter <<Enumeration>> {
    A
    B
    C
    D
    E
    F
    G
    H
    I
    J
    K
    L
    M
    N
    O
    P
    Q
    R
    S
    T
    U
    V
    W
    X
    Y
    Z
    .
}

Class Word {
    generateAFiveLetterWord()
    generateASixLetterWord()
    generateASevenLetterWord()
}

Person }o--|| Role : role >
Account ||--|| Person : account <
Game }o--|| Person : games <
Game ||--|{ Round : rounds >
Round ||--|| RoundDTO : roundDTO >
Feedback ||--o{ FeedbackItem : feedbackItems >
Feedback }o--|| Round : feedback <
Feedback }o--|| RoundDTO : feedback <
Letter "5...7" --o| Word: letters <
Word "1...5" }|--|| Round : hint <
Word "1...5" }|--|| RoundDTO: hint <
Word "1...5" }|--|| Round : guess <
Word "1...5" }|--|| RoundDTO: guess <
@enduml